#!/bin/bash
# Conduit Pipeline Deployment Script
# Generated by kc2con

set -e

CONDUIT_URL="${CONDUIT_URL:-http://localhost:8080}"

echo "🚀 Deploying Conduit pipelines..."
echo "   Target: $CONDUIT_URL"
echo ""

# Function to create pipeline
create_pipeline() {
    local pipeline_file=$1
    local pipeline_name=$(basename "$pipeline_file" .yaml)
    
    echo "Creating pipeline: $pipeline_name"
    
    # Using Conduit CLI
    # conduit pipeline create --file "$pipeline_file"
    
    # Or using API
    curl -X POST \
        -H "Content-Type: application/yaml" \
        -d "@$pipeline_file" \
        "$CONDUIT_URL/v1/pipelines" || {
        echo "❌ Failed to create pipeline: $pipeline_name"
        return 1
    }
    
    echo "✅ Created pipeline: $pipeline_name"
}

# Deploy pipelines
create_pipeline "pipelines/mysql-source-customers.yaml"
create_pipeline "pipelines/postgres-sink.yaml"
create_pipeline "pipelines/s3-backup.yaml"

echo ""
echo "✨ Deployment complete!"
echo ""
echo "To start pipelines:"
echo "  conduit pipeline start --all"
echo ""
echo "To check status:"
echo "  conduit pipeline list"
